### PR TITLE
Update to newest version of sbtrc

### PR DESCRIPTION
**Pull request by sschaef**
This update makes sbt integration in Scala IDE fit for service. Its only feature so far is to import sbt projects. But even that doesn't always work. In contrast to the sbt plugin sbteclipse only very simple project layouts are supported.

### CODE REVIEW

**Comment by dragos** [comment]
Strange failure:

```
[ERROR]   The project org.scala-ide:org.scala-ide.sbt.build:0.1.0-SNAPSHOT (/mnt/ide/jenkinside/jenkinside-a1/workspace/ghprb-sbt-integration-2.10.x/sbt-integration/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact org.scala-ide:plugin-profiles:pom:1.0.9 in typesafe releases (http://repo.typesafe.com/typesafe/releases) and 'parent.relativePath' points at wrong local POM @ line 9, column 11 -> [Help 2]
```

It looks like it can't find the latest release of plugin-profiles. I have no idea why it looks for it in the typesafe repo, instead of Maven Central..

**Comment by sschaef** [comment]
The error is correct, the dependency indeed does not exist. It was in the staging area of sonatype. I didn't read the description up to the end, where it says that the dependency needs to be released manually from the staging area. I did this now, should then be available soon.

**Comment by sschaef** [comment]
@dragos it looks like jenkins is hardcoded to run the build with outdated parameters. It should execute the `build.sh` file in the root folder.

**Comment by dragos** [comment]
retest this please

**Comment by sschaef** [comment]
@dragos Thanks for having a look!

**Comment by dragos** [comment]
I'll say LGTM, though I didn't really try it.

**Pull request merged**
